### PR TITLE
Update nl_NL.json

### PR DESCRIPTION
**Pull request by Pyrofox**
Added the new lines, removed others and changed the Search translation.

### CODE REVIEW

**Comment by rmcauley** [comment]
Thanks a bunch!

What diff tool are you using by the way?  I see you inserting comments from the en_MASTER file. :)

**Comment by Pyrofox** [comment]
No problem ;)

I'm not using a diff tool. Every time I change the new lines, I put the
English version besides the Dutch and check the whole file. If I see some
lines that are new or changed, I just copy/paste and then translate them.
There were a few comments in the English file so I just copied them over to
the Dutch file, it's easier for me anyway :)
But now that you mention it, using a diff tool would be extremely helpful
:P if you know a good one (that runs on Mac), let me know ;)

**Comment by rmcauley** [comment]
My friend says he uses SourceTree.

**Comment by Pyrofox** [comment]
Looks good, I'll check it out tomorrow, thanks ;)

**Pull request merged**
