### PR TITLE
Album art scan fix

### PR DESCRIPTION
**Pull request by williamjacksn**
If the path to the image file contains a `'` (single quote), the album art would not be applied to the appropriate album.

### CODE REVIEW

**Comment by rmcauley** [comment]
Ugh, this line.  I'll test it out on my Windows box at home in a day or two.

**Comment by rmcauley** [comment]
Seems fine.  Makes me nervous, but seems fine. :)

**Comment by williamjacksn** [comment]
Get VirtualBox, stop developing on Windows, and we can dispense with the workarounds. :)

**Comment by rmcauley** [comment]
I may not be the only one developing on Windows, and my tablet doesn't have the RAM horsepower to run a VM at the moment. :)

**Pull request merged**
